server:
  port: 8090


spring:
  application:
    name: msvc-student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # Corregido: Debe ser el nombre completo de la clase del driver JDBC
    url: jdbc:mysql://localhost:3306/studentDb   # Corregido: URL correcta de conexión a la base de datos MySQL
    username: root
    password : Rlwl2023.
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka